trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

container: chinedufn/blender-rustlang:latest

# TODO: Remove once we port test suite to Rust
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    xfvb-run npm run test
  displayName: 'npm install and xvfb0test'
